package com.havenbank.backend.audit.domain;

/**
 * Enumerated security-relevant actions recorded on the audit trail.
 */
public enum AuditAction {
    REGISTER,
    EMAIL_VERIFIED,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,
    OTP_ISSUED,
    OTP_VERIFIED,
    ROLE_CREATED,
    USER_ROLES_UPDATED,
    USER_LOCKED,
    USER_DEACTIVATED,
    AUDIT_VIEWED,
    ACCOUNT_OPENED,
    ACCOUNT_CLOSED,
    DEPOSIT,
    WITHDRAWAL,
    TRANSFER,
    NOTIFICATION_PREFS_UPDATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    ROLE_PERMISSIONS_UPDATED,
    USER_UNLOCKED,
    FEE_SCHEDULE_VERSIONED,
    POLICY_VERSIONED,
    RATE_LIMITED,
    ACCOUNT_LOCKED,
    BENEFICIARY_ADDED,
    BENEFICIARY_UPDATED,
    BENEFICIARY_DELETED,
    REFRESH_TOKEN_REUSE,
    NOTIFICATION_REQUEUED
}