package com.havenbank.backend.shared.web;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.MDC;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.UUID;

/**
 * Assigns a correlation id to every inbound request at the outermost point, before any business
 * logic runs (FR-5.4). The id is <strong>always generated by the system</strong>, never taken from
 * a client-supplied header: this filter is the trust boundary (there is no gateway in front of it),
 * so honouring an inbound {@code X-Correlation-Id} would let a caller forge or collide correlation
 * ids and merge their activity into another request's trace. The generated id is placed in the SLF4J
 * {@link MDC} so it appears on every log line, and is echoed back on the response for client-side
 * tracing only.
 *
 * <p>If a trusted upstream (e.g. a future API gateway) ever needs to propagate an inbound id, gate
 * that on an explicit "trusted proxy" configuration flag and still reject anything that is not a
 * well-formed {@link UUID} — do not simply trust the header.
 */
@Order(org.springframework.core.Ordered.HIGHEST_PRECEDENCE)
@Component
public class CorrelationIdFilter extends OncePerRequestFilter {

    public static final String HEADER = "X-Correlation-Id";
    public static final String MDC_KEY = "correlationId";

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
                                    FilterChain filterChain) throws ServletException, IOException {
        String correlationId = UUID.randomUUID().toString();
        MDC.put(MDC_KEY, correlationId);
        response.setHeader(HEADER, correlationId);
        try {
            filterChain.doFilter(request, response);
        } finally {
            MDC.remove(MDC_KEY);
        }
    }
}
